PART=2
.PHONY: diffusion
diffusion:
	python3 diffusion.py --part=$(PART)

.PHONY: rwalk
rwalk:
	python3 rwalk.py --part=$(PART)

.PHONY: rnumbers
rnumbers:
	python3 rnumbers.py --part=$(PART)

.PHONY: gases
gases:
	python3 gases.py --part=$(PART)
